### ISSUE TITLE
Huanglong & Qilin Raid

### ISSUE THREAD

**Issue by zorkings** [steve1316/granblue-automation-pyautogui#56]
Would it be possible to add this raid to the selection options?

**Comment by steve1316** [comment]
Just pushed an update giving support for the "Huanglong and Qilin (Impossible)" Raid. Let me know how it goes!

**Comment by zorkings** [comment]
New raid finding is working fine but I've noticed two things;

The default one punch and exit script is in invalid syntax to exit and is why i was confused as to why my previous combat script was not exiting (used that one as an example)

If you have 5 pending battles from running an exit script in raids when the bot goes to enter a new raid the "Please check pending battles" pop up causes an error stopping the script seems it thinks it is the berry automated usage popup

**Comment by steve1316** [comment]
Thank you for letting me know. I just pushed updates fixing these two bugs. Let me know how it goes!

**Comment by zorkings** [comment]
Now claims pending battles but however after claiming final one and clicking quest button it gets stuck thinking it has entered a raid id.

**Comment by steve1316** [comment]
Just pushed an update fixing that. Let me know how it goes!

**Comment by zorkings** [comment]
Still an issue, now it is going into crate at homescreen after clearing the 5 pending

**Comment by steve1316** [comment]
Can you describe the situation in more detail? I tested it after clearing 5 Pending Battles and it successfully cleared them all, went back to the Home screen, and then proceeded to the Raid screen in order to farm more Raids.

**Comment by zorkings** [comment]
After clearing pending battles it pressed home button.
Log below is after it reached homescreen
![image](https://user-images.githubusercontent.com/77841008/128586832-9ab45bde-b301-44e4-933e-7b9ef88abe8f.png)
Then clicked the crate on home screen

**Comment by steve1316** [comment]
Can you paste the full text file log here by clicking on the "Save Logs" button on the UI and uploading the .txt file here?

**Comment by zorkings** [comment]
[logs.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/6949132/logs.txt)

**Comment by steve1316** [comment]
Thank you for posting the log. Finally managed to track down the issue since I was not able to replicate it normally on my end.

**Comment by zorkings** [comment]
Successfully collected raids, will close as I believe it is now fixed.
